name: very_good_coffee_app
description: this project is a Tech Assignment for Very Good Ventures
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_card_swiper: ^7.0.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  network_image_mock: ^2.1.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
